version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    environment:
      DATABASE_URL: "file:./dev.db"
      PORT: 3001
      NODE_ENV: development
      CORS_ORIGIN: "http://localhost:5173"
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    command: ["pnpm", "dev"]

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      VITE_API_URL: "http://localhost:3001"
    command: ["pnpm", "dev", "--host"]
    depends_on:
      - api
